### ISSUE TITLE
update to exiftool 12.50

### ISSUE THREAD

**Issue by richardmonette** [exiftool-rb/exiftool_vendored.rb#19]
Hello! I noticed that exiftool has released a new production version at 12.50, see: https://exiftool.org/history.html

@morozgrafix would it be possible to please do an update similar to https://github.com/exiftool-rb/exiftool_vendored.rb/commit/c154ac88071e480d595fa47140eb65487d4f2b07 moving to version 12.50?

Thanks!

edit: if it would be helpful I can put up a pull request with the changes : )

**Comment by morozgrafix** [comment]
@richardmonette thanks for opening the issue. Sorry I haven't had a lot of spare time to maintain this repo. I will try to push an update sometime this week.

**Comment by morozgrafix** [comment]
@richardmonette Just updated to v.12.50 and gem has been pushed to RubyGems https://rubygems.org/gems/exiftool_vendored/versions/12.50.0

Thank you.
